from setuptools import setup

setup(
    name='ssd_robosub',
    version='',
    packages=['venv.lib.python3.7.site-packages.PIL', 'venv.lib.python3.7.site-packages.cv2',
              'venv.lib.python3.7.site-packages.cv2.data', 'venv.lib.python3.7.site-packages.pip',
              'venv.lib.python3.7.site-packages.pip._vendor', 'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.tlz',
              'venv.lib.python3.7.site-packages.zmq', 'venv.lib.python3.7.site-packages.zmq.log',
              'venv.lib.python3.7.site-packages.zmq.ssh', 'venv.lib.python3.7.site-packages.zmq.auth',
              'venv.lib.python3.7.site-packages.zmq.auth.asyncio', 'venv.lib.python3.7.site-packages.zmq.green',
              'venv.lib.python3.7.site-packages.zmq.green.eventloop', 'venv.lib.python3.7.site-packages.zmq.sugar',
              'venv.lib.python3.7.site-packages.zmq.tests', 'venv.lib.python3.7.site-packages.zmq.tests.asyncio',
              'venv.lib.python3.7.site-packages.zmq.utils', 'venv.lib.python3.7.site-packages.zmq.asyncio',
              'venv.lib.python3.7.site-packages.zmq.backend', 'venv.lib.python3.7.site-packages.zmq.backend.cffi',
              'venv.lib.python3.7.site-packages.zmq.backend.cython', 'venv.lib.python3.7.site-packages.zmq.devices',
              'venv.lib.python3.7.site-packages.zmq.eventloop',
              'venv.lib.python3.7.site-packages.zmq.eventloop.minitornado',
              'venv.lib.python3.7.site-packages.zmq.eventloop.minitornado.platform',
              'venv.lib.python3.7.site-packages.dask', 'venv.lib.python3.7.site-packages.dask.bag',
              'venv.lib.python3.7.site-packages.dask.bag.tests', 'venv.lib.python3.7.site-packages.dask.array',
              'venv.lib.python3.7.site-packages.dask.array.tests', 'venv.lib.python3.7.site-packages.dask.bytes',
              'venv.lib.python3.7.site-packages.dask.bytes.tests', 'venv.lib.python3.7.site-packages.dask.tests',
              'venv.lib.python3.7.site-packages.dask.dataframe', 'venv.lib.python3.7.site-packages.dask.dataframe.io',
              'venv.lib.python3.7.site-packages.dask.dataframe.io.tests',
              'venv.lib.python3.7.site-packages.dask.dataframe.tests',
              'venv.lib.python3.7.site-packages.dask.dataframe.tseries',
              'venv.lib.python3.7.site-packages.dask.dataframe.tseries.tests',
              'venv.lib.python3.7.site-packages.dask.diagnostics',
              'venv.lib.python3.7.site-packages.dask.diagnostics.tests', 'venv.lib.python3.7.site-packages.jedi',
              'venv.lib.python3.7.site-packages.jedi.api', 'venv.lib.python3.7.site-packages.jedi.common',
              'venv.lib.python3.7.site-packages.jedi.evaluate',
              'venv.lib.python3.7.site-packages.jedi.evaluate.context',
              'venv.lib.python3.7.site-packages.jedi.evaluate.compiled',
              'venv.lib.python3.7.site-packages.jedi.evaluate.compiled.subprocess',
              'venv.lib.python3.7.site-packages.pytz', 'venv.lib.python3.7.site-packages.pywt',
              'venv.lib.python3.7.site-packages.pywt.data', 'venv.lib.python3.7.site-packages.pywt._extensions',
              'venv.lib.python3.7.site-packages.rope', 'venv.lib.python3.7.site-packages.rope.base',
              'venv.lib.python3.7.site-packages.rope.base.oi',
              'venv.lib.python3.7.site-packages.rope.base.oi.type_hinting',
              'venv.lib.python3.7.site-packages.rope.base.oi.type_hinting.providers',
              'venv.lib.python3.7.site-packages.rope.base.oi.type_hinting.resolvers',
              'venv.lib.python3.7.site-packages.rope.base.utils', 'venv.lib.python3.7.site-packages.rope.contrib',
              'venv.lib.python3.7.site-packages.rope.refactor',
              'venv.lib.python3.7.site-packages.rope.refactor.importutils', 'venv.lib.python3.7.site-packages.parso',
              'venv.lib.python3.7.site-packages.parso.pgen2', 'venv.lib.python3.7.site-packages.parso.python',
              'venv.lib.python3.7.site-packages.scipy', 'venv.lib.python3.7.site-packages.scipy.io',
              'venv.lib.python3.7.site-packages.scipy.io.arff', 'venv.lib.python3.7.site-packages.scipy.io.arff.tests',
              'venv.lib.python3.7.site-packages.scipy.io.tests', 'venv.lib.python3.7.site-packages.scipy.io.matlab',
              'venv.lib.python3.7.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.7.site-packages.scipy.odr', 'venv.lib.python3.7.site-packages.scipy.odr.tests',
              'venv.lib.python3.7.site-packages.scipy._lib', 'venv.lib.python3.7.site-packages.scipy._lib.tests',
              'venv.lib.python3.7.site-packages.scipy.misc', 'venv.lib.python3.7.site-packages.scipy.misc.tests',
              'venv.lib.python3.7.site-packages.scipy.stats', 'venv.lib.python3.7.site-packages.scipy.stats.tests',
              'venv.lib.python3.7.site-packages.scipy.linalg', 'venv.lib.python3.7.site-packages.scipy.linalg.tests',
              'venv.lib.python3.7.site-packages.scipy.signal', 'venv.lib.python3.7.site-packages.scipy.signal.tests',
              'venv.lib.python3.7.site-packages.scipy.signal.windows', 'venv.lib.python3.7.site-packages.scipy.sparse',
              'venv.lib.python3.7.site-packages.scipy.sparse.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.7.site-packages.scipy.cluster', 'venv.lib.python3.7.site-packages.scipy.cluster.tests',
              'venv.lib.python3.7.site-packages.scipy.fftpack', 'venv.lib.python3.7.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.7.site-packages.scipy.ndimage', 'venv.lib.python3.7.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.7.site-packages.scipy.spatial', 'venv.lib.python3.7.site-packages.scipy.spatial.tests',
              'venv.lib.python3.7.site-packages.scipy.spatial.transform',
              'venv.lib.python3.7.site-packages.scipy.spatial.transform.tests',
              'venv.lib.python3.7.site-packages.scipy.special', 'venv.lib.python3.7.site-packages.scipy.special.tests',
              'venv.lib.python3.7.site-packages.scipy.special._precompute',
              'venv.lib.python3.7.site-packages.scipy.optimize', 'venv.lib.python3.7.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.7.site-packages.scipy.optimize.tests',
              'venv.lib.python3.7.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.7.site-packages.scipy.optimize._shgo_lib',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.7.site-packages.scipy.constants',
              'venv.lib.python3.7.site-packages.scipy.constants.tests',
              'venv.lib.python3.7.site-packages.scipy.integrate',
              'venv.lib.python3.7.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.7.site-packages.scipy.integrate.tests',
              'venv.lib.python3.7.site-packages.scipy.interpolate',
              'venv.lib.python3.7.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.7.site-packages.scipy._build_utils', 'venv.lib.python3.7.site-packages.toolz',
              'venv.lib.python3.7.site-packages.toolz.curried', 'venv.lib.python3.7.site-packages.toolz.sandbox',
              'venv.lib.python3.7.site-packages.bleach', 'venv.lib.python3.7.site-packages.bleach._vendor',
              'venv.lib.python3.7.site-packages.bleach._vendor.html5lib',
              'venv.lib.python3.7.site-packages.bleach._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.bleach._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.bleach._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.bleach._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.bleach._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.imgaug', 'venv.lib.python3.7.site-packages.imgaug.external',
              'venv.lib.python3.7.site-packages.imgaug.augmenters', 'venv.lib.python3.7.site-packages.jinja2',
              'venv.lib.python3.7.site-packages.pandas', 'venv.lib.python3.7.site-packages.pandas.io',
              'venv.lib.python3.7.site-packages.pandas.io.sas', 'venv.lib.python3.7.site-packages.pandas.io.json',
              'venv.lib.python3.7.site-packages.pandas.io.formats',
              'venv.lib.python3.7.site-packages.pandas.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.io.clipboard', 'venv.lib.python3.7.site-packages.pandas.api',
              'venv.lib.python3.7.site-packages.pandas.api.types',
              'venv.lib.python3.7.site-packages.pandas.api.extensions', 'venv.lib.python3.7.site-packages.pandas.core',
              'venv.lib.python3.7.site-packages.pandas.core.util', 'venv.lib.python3.7.site-packages.pandas.core.tools',
              'venv.lib.python3.7.site-packages.pandas.core.arrays',
              'venv.lib.python3.7.site-packages.pandas.core.dtypes',
              'venv.lib.python3.7.site-packages.pandas.core.sparse',
              'venv.lib.python3.7.site-packages.pandas.core.groupby',
              'venv.lib.python3.7.site-packages.pandas.core.indexes',
              'venv.lib.python3.7.site-packages.pandas.core.reshape',
              'venv.lib.python3.7.site-packages.pandas.core.internals',
              'venv.lib.python3.7.site-packages.pandas.core.computation',
              'venv.lib.python3.7.site-packages.pandas.util', 'venv.lib.python3.7.site-packages.pandas._libs',
              'venv.lib.python3.7.site-packages.pandas._libs.tslibs', 'venv.lib.python3.7.site-packages.pandas.tests',
              'venv.lib.python3.7.site-packages.pandas.tests.io',
              'venv.lib.python3.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.7.site-packages.pandas.tests.io.json',
              'venv.lib.python3.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.tests.api', 'venv.lib.python3.7.site-packages.pandas.tests.util',
              'venv.lib.python3.7.site-packages.pandas.tests.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.tools',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.arrays.categorical',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes.cast',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.7.site-packages.pandas.tests.series',
              'venv.lib.python3.7.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.7.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.7.site-packages.pandas.tests.generic',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.multi',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.multiindex',
              'venv.lib.python3.7.site-packages.pandas.tests.plotting',
              'venv.lib.python3.7.site-packages.pandas.tests.resample',
              'venv.lib.python3.7.site-packages.pandas.tests.extension',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.arrow',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.7.site-packages.pandas.tests.internals',
              'venv.lib.python3.7.site-packages.pandas.tests.arithmetic',
              'venv.lib.python3.7.site-packages.pandas.tests.reductions',
              'venv.lib.python3.7.site-packages.pandas.tests.computation',
              'venv.lib.python3.7.site-packages.pandas.arrays', 'venv.lib.python3.7.site-packages.pandas.compat',
              'venv.lib.python3.7.site-packages.pandas.compat.numpy', 'venv.lib.python3.7.site-packages.pandas.errors',
              'venv.lib.python3.7.site-packages.pandas.tseries', 'venv.lib.python3.7.site-packages.pandas.plotting',
              'venv.lib.python3.7.site-packages.tables', 'venv.lib.python3.7.site-packages.tables.misc',
              'venv.lib.python3.7.site-packages.tables.nodes', 'venv.lib.python3.7.site-packages.tables.nodes.tests',
              'venv.lib.python3.7.site-packages.tables.tests', 'venv.lib.python3.7.site-packages.tables.scripts',
              'venv.lib.python3.7.site-packages.IPython', 'venv.lib.python3.7.site-packages.IPython.lib',
              'venv.lib.python3.7.site-packages.IPython.lib.tests', 'venv.lib.python3.7.site-packages.IPython.core',
              'venv.lib.python3.7.site-packages.IPython.core.tests',
              'venv.lib.python3.7.site-packages.IPython.core.magics', 'venv.lib.python3.7.site-packages.IPython.utils',
              'venv.lib.python3.7.site-packages.IPython.utils.tests', 'venv.lib.python3.7.site-packages.IPython.kernel',
              'venv.lib.python3.7.site-packages.IPython.testing',
              'venv.lib.python3.7.site-packages.IPython.testing.tests',
              'venv.lib.python3.7.site-packages.IPython.testing.plugin',
              'venv.lib.python3.7.site-packages.IPython.external',
              'venv.lib.python3.7.site-packages.IPython.external.decorators',
              'venv.lib.python3.7.site-packages.IPython.terminal',
              'venv.lib.python3.7.site-packages.IPython.terminal.tests',
              'venv.lib.python3.7.site-packages.IPython.terminal.pt_inputhooks',
              'venv.lib.python3.7.site-packages.IPython.sphinxext',
              'venv.lib.python3.7.site-packages.IPython.extensions',
              'venv.lib.python3.7.site-packages.IPython.extensions.tests', 'venv.lib.python3.7.site-packages.imageio',
              'venv.lib.python3.7.site-packages.imageio.core', 'venv.lib.python3.7.site-packages.imageio.plugins',
              'venv.lib.python3.7.site-packages.numexpr', 'venv.lib.python3.7.site-packages.numexpr.tests',
              'venv.lib.python3.7.site-packages.pexpect', 'venv.lib.python3.7.site-packages.shapely',
              'venv.lib.python3.7.site-packages.shapely.examples', 'venv.lib.python3.7.site-packages.shapely.geometry',
              'venv.lib.python3.7.site-packages.shapely.speedups',
              'venv.lib.python3.7.site-packages.shapely.algorithms',
              'venv.lib.python3.7.site-packages.shapely.vectorized', 'venv.lib.python3.7.site-packages.skimage',
              'venv.lib.python3.7.site-packages.skimage.io', 'venv.lib.python3.7.site-packages.skimage.io.tests',
              'venv.lib.python3.7.site-packages.skimage.io._plugins', 'venv.lib.python3.7.site-packages.skimage.data',
              'venv.lib.python3.7.site-packages.skimage.data.tests', 'venv.lib.python3.7.site-packages.skimage.draw',
              'venv.lib.python3.7.site-packages.skimage.draw.tests', 'venv.lib.python3.7.site-packages.skimage.util',
              'venv.lib.python3.7.site-packages.skimage.util.tests', 'venv.lib.python3.7.site-packages.skimage.color',
              'venv.lib.python3.7.site-packages.skimage.color.tests', 'venv.lib.python3.7.site-packages.skimage.graph',
              'venv.lib.python3.7.site-packages.skimage.graph.tests', 'venv.lib.python3.7.site-packages.skimage.future',
              'venv.lib.python3.7.site-packages.skimage.future.graph',
              'venv.lib.python3.7.site-packages.skimage.novice',
              'venv.lib.python3.7.site-packages.skimage.novice.tests',
              'venv.lib.python3.7.site-packages.skimage.viewer',
              'venv.lib.python3.7.site-packages.skimage.viewer.tests',
              'venv.lib.python3.7.site-packages.skimage.viewer.utils',
              'venv.lib.python3.7.site-packages.skimage.viewer.plugins',
              'venv.lib.python3.7.site-packages.skimage.viewer.viewers',
              'venv.lib.python3.7.site-packages.skimage.viewer.widgets',
              'venv.lib.python3.7.site-packages.skimage.viewer.canvastools',
              'venv.lib.python3.7.site-packages.skimage._shared',
              'venv.lib.python3.7.site-packages.skimage._shared.tests',
              'venv.lib.python3.7.site-packages.skimage.feature',
              'venv.lib.python3.7.site-packages.skimage.feature.tests',
              'venv.lib.python3.7.site-packages.skimage.filters',
              'venv.lib.python3.7.site-packages.skimage.filters.rank',
              'venv.lib.python3.7.site-packages.skimage.filters.rank.tests',
              'venv.lib.python3.7.site-packages.skimage.filters.tests',
              'venv.lib.python3.7.site-packages.skimage.measure',
              'venv.lib.python3.7.site-packages.skimage.measure.tests',
              'venv.lib.python3.7.site-packages.skimage.scripts', 'venv.lib.python3.7.site-packages.skimage.exposure',
              'venv.lib.python3.7.site-packages.skimage.exposure.tests',
              'venv.lib.python3.7.site-packages.skimage.external',
              'venv.lib.python3.7.site-packages.skimage.external.tifffile',
              'venv.lib.python3.7.site-packages.skimage.transform',
              'venv.lib.python3.7.site-packages.skimage.transform.tests',
              'venv.lib.python3.7.site-packages.skimage.morphology',
              'venv.lib.python3.7.site-packages.skimage.morphology.tests',
              'venv.lib.python3.7.site-packages.skimage.restoration',
              'venv.lib.python3.7.site-packages.skimage.restoration.tests',
              'venv.lib.python3.7.site-packages.skimage.segmentation',
              'venv.lib.python3.7.site-packages.skimage.segmentation.tests', 'venv.lib.python3.7.site-packages.tornado',
              'venv.lib.python3.7.site-packages.tornado.test', 'venv.lib.python3.7.site-packages.tornado.platform',
              'venv.lib.python3.7.site-packages.wcwidth', 'venv.lib.python3.7.site-packages.wcwidth.tests',
              'venv.lib.python3.7.site-packages.backcall', 'venv.lib.python3.7.site-packages.nbformat',
              'venv.lib.python3.7.site-packages.nbformat.v1', 'venv.lib.python3.7.site-packages.nbformat.v1.tests',
              'venv.lib.python3.7.site-packages.nbformat.v2', 'venv.lib.python3.7.site-packages.nbformat.v2.tests',
              'venv.lib.python3.7.site-packages.nbformat.v3', 'venv.lib.python3.7.site-packages.nbformat.v3.tests',
              'venv.lib.python3.7.site-packages.nbformat.v4', 'venv.lib.python3.7.site-packages.nbformat.v4.tests',
              'venv.lib.python3.7.site-packages.nbformat.tests', 'venv.lib.python3.7.site-packages.networkx',
              'venv.lib.python3.7.site-packages.networkx.tests', 'venv.lib.python3.7.site-packages.networkx.utils',
              'venv.lib.python3.7.site-packages.networkx.linalg', 'venv.lib.python3.7.site-packages.networkx.classes',
              'venv.lib.python3.7.site-packages.networkx.drawing', 'venv.lib.python3.7.site-packages.networkx.testing',
              'venv.lib.python3.7.site-packages.networkx.readwrite',
              'venv.lib.python3.7.site-packages.networkx.readwrite.json_graph',
              'venv.lib.python3.7.site-packages.networkx.algorithms',
              'venv.lib.python3.7.site-packages.networkx.algorithms.flow',
              'venv.lib.python3.7.site-packages.networkx.algorithms.tree',
              'venv.lib.python3.7.site-packages.networkx.algorithms.coloring',
              'venv.lib.python3.7.site-packages.networkx.algorithms.bipartite',
              'venv.lib.python3.7.site-packages.networkx.algorithms.community',
              'venv.lib.python3.7.site-packages.networkx.algorithms.operators',
              'venv.lib.python3.7.site-packages.networkx.algorithms.traversal',
              'venv.lib.python3.7.site-packages.networkx.algorithms.centrality',
              'venv.lib.python3.7.site-packages.networkx.algorithms.components',
              'venv.lib.python3.7.site-packages.networkx.algorithms.isomorphism',
              'venv.lib.python3.7.site-packages.networkx.algorithms.connectivity',
              'venv.lib.python3.7.site-packages.networkx.algorithms.approximation',
              'venv.lib.python3.7.site-packages.networkx.algorithms.assortativity',
              'venv.lib.python3.7.site-packages.networkx.algorithms.link_analysis',
              'venv.lib.python3.7.site-packages.networkx.algorithms.shortest_paths',
              'venv.lib.python3.7.site-packages.networkx.algorithms.node_classification',
              'venv.lib.python3.7.site-packages.networkx.generators', 'venv.lib.python3.7.site-packages.notebook',
              'venv.lib.python3.7.site-packages.notebook.auth', 'venv.lib.python3.7.site-packages.notebook.auth.tests',
              'venv.lib.python3.7.site-packages.notebook.base', 'venv.lib.python3.7.site-packages.notebook.edit',
              'venv.lib.python3.7.site-packages.notebook.i18n', 'venv.lib.python3.7.site-packages.notebook.tree',
              'venv.lib.python3.7.site-packages.notebook.tree.tests', 'venv.lib.python3.7.site-packages.notebook.view',
              'venv.lib.python3.7.site-packages.notebook.files', 'venv.lib.python3.7.site-packages.notebook.tests',
              'venv.lib.python3.7.site-packages.notebook.tests.selenium',
              'venv.lib.python3.7.site-packages.notebook.bundler',
              'venv.lib.python3.7.site-packages.notebook.bundler.tests',
              'venv.lib.python3.7.site-packages.notebook.notebook',
              'venv.lib.python3.7.site-packages.notebook.services',
              'venv.lib.python3.7.site-packages.notebook.services.api',
              'venv.lib.python3.7.site-packages.notebook.services.api.tests',
              'venv.lib.python3.7.site-packages.notebook.services.config',
              'venv.lib.python3.7.site-packages.notebook.services.config.tests',
              'venv.lib.python3.7.site-packages.notebook.services.kernels',
              'venv.lib.python3.7.site-packages.notebook.services.kernels.tests',
              'venv.lib.python3.7.site-packages.notebook.services.contents',
              'venv.lib.python3.7.site-packages.notebook.services.contents.tests',
              'venv.lib.python3.7.site-packages.notebook.services.security',
              'venv.lib.python3.7.site-packages.notebook.services.sessions',
              'venv.lib.python3.7.site-packages.notebook.services.sessions.tests',
              'venv.lib.python3.7.site-packages.notebook.services.nbconvert',
              'venv.lib.python3.7.site-packages.notebook.services.nbconvert.tests',
              'venv.lib.python3.7.site-packages.notebook.services.kernelspecs',
              'venv.lib.python3.7.site-packages.notebook.services.kernelspecs.tests',
              'venv.lib.python3.7.site-packages.notebook.terminal',
              'venv.lib.python3.7.site-packages.notebook.nbconvert',
              'venv.lib.python3.7.site-packages.notebook.nbconvert.tests',
              'venv.lib.python3.7.site-packages.notebook.kernelspecs', 'venv.lib.python3.7.site-packages.pygments',
              'venv.lib.python3.7.site-packages.pygments.lexers', 'venv.lib.python3.7.site-packages.pygments.styles',
              'venv.lib.python3.7.site-packages.pygments.filters',
              'venv.lib.python3.7.site-packages.pygments.formatters', 'venv.lib.python3.7.site-packages.testpath',
              'venv.lib.python3.7.site-packages.ipykernel', 'venv.lib.python3.7.site-packages.ipykernel.gui',
              'venv.lib.python3.7.site-packages.ipykernel.comm', 'venv.lib.python3.7.site-packages.ipykernel.pylab',
              'venv.lib.python3.7.site-packages.ipykernel.tests',
              'venv.lib.python3.7.site-packages.ipykernel.inprocess',
              'venv.lib.python3.7.site-packages.ipykernel.inprocess.tests',
              'venv.lib.python3.7.site-packages.nbconvert', 'venv.lib.python3.7.site-packages.nbconvert.tests',
              'venv.lib.python3.7.site-packages.nbconvert.utils',
              'venv.lib.python3.7.site-packages.nbconvert.utils.tests',
              'venv.lib.python3.7.site-packages.nbconvert.filters',
              'venv.lib.python3.7.site-packages.nbconvert.filters.tests',
              'venv.lib.python3.7.site-packages.nbconvert.writers',
              'venv.lib.python3.7.site-packages.nbconvert.writers.tests',
              'venv.lib.python3.7.site-packages.nbconvert.exporters',
              'venv.lib.python3.7.site-packages.nbconvert.exporters.tests',
              'venv.lib.python3.7.site-packages.nbconvert.resources',
              'venv.lib.python3.7.site-packages.nbconvert.preprocessors',
              'venv.lib.python3.7.site-packages.nbconvert.preprocessors.tests',
              'venv.lib.python3.7.site-packages.nbconvert.postprocessors',
              'venv.lib.python3.7.site-packages.nbconvert.postprocessors.tests',
              'venv.lib.python3.7.site-packages.qtconsole', 'venv.lib.python3.7.site-packages.qtconsole.tests',
              'venv.lib.python3.7.site-packages.terminado', 'venv.lib.python3.7.site-packages.terminado.tests',
              'venv.lib.python3.7.site-packages.traitlets', 'venv.lib.python3.7.site-packages.traitlets.tests',
              'venv.lib.python3.7.site-packages.traitlets.utils',
              'venv.lib.python3.7.site-packages.traitlets.utils.tests',
              'venv.lib.python3.7.site-packages.traitlets.config',
              'venv.lib.python3.7.site-packages.traitlets.config.tests', 'venv.lib.python3.7.site-packages.defusedxml',
              'venv.lib.python3.7.site-packages.ipywidgets', 'venv.lib.python3.7.site-packages.ipywidgets.tests',
              'venv.lib.python3.7.site-packages.ipywidgets.widgets',
              'venv.lib.python3.7.site-packages.ipywidgets.widgets.tests',
              'venv.lib.python3.7.site-packages.markupsafe', 'venv.lib.python3.7.site-packages.matplotlib',
              'venv.lib.python3.7.site-packages.matplotlib.tri', 'venv.lib.python3.7.site-packages.matplotlib.axes',
              'venv.lib.python3.7.site-packages.matplotlib.cbook', 'venv.lib.python3.7.site-packages.matplotlib.style',
              'venv.lib.python3.7.site-packages.matplotlib.tests', 'venv.lib.python3.7.site-packages.matplotlib.compat',
              'venv.lib.python3.7.site-packages.matplotlib.testing',
              'venv.lib.python3.7.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.7.site-packages.matplotlib.backends',
              'venv.lib.python3.7.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.7.site-packages.matplotlib.projections', 'venv.lib.python3.7.site-packages.ptyprocess',
              'venv.lib.python3.7.site-packages.send2trash', 'venv.lib.python3.7.site-packages.setuptools',
              'venv.lib.python3.7.site-packages.setuptools.extern',
              'venv.lib.python3.7.site-packages.setuptools._vendor',
              'venv.lib.python3.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.7.site-packages.setuptools.command', 'venv.lib.python3.7.site-packages.cloudpickle',
              'venv.lib.python3.7.site-packages.jupyter_core', 'venv.lib.python3.7.site-packages.jupyter_core.tests',
              'venv.lib.python3.7.site-packages.jupyter_core.utils',
              'venv.lib.python3.7.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.7.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axisartist',
              'venv.lib.python3.7.site-packages.webencodings', 'venv.lib.python3.7.site-packages.pkg_resources',
              'venv.lib.python3.7.site-packages.pkg_resources.extern',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor',
              'venv.lib.python3.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.7.site-packages.jupyter_client',
              'venv.lib.python3.7.site-packages.jupyter_client.tests',
              'venv.lib.python3.7.site-packages.jupyter_client.ioloop',
              'venv.lib.python3.7.site-packages.jupyter_client.blocking',
              'venv.lib.python3.7.site-packages.prompt_toolkit',
              'venv.lib.python3.7.site-packages.prompt_toolkit.input',
              'venv.lib.python3.7.site-packages.prompt_toolkit.layout',
              'venv.lib.python3.7.site-packages.prompt_toolkit.lexers',
              'venv.lib.python3.7.site-packages.prompt_toolkit.output',
              'venv.lib.python3.7.site-packages.prompt_toolkit.styles',
              'venv.lib.python3.7.site-packages.prompt_toolkit.contrib',
              'venv.lib.python3.7.site-packages.prompt_toolkit.contrib.telnet',
              'venv.lib.python3.7.site-packages.prompt_toolkit.contrib.completers',
              'venv.lib.python3.7.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.lib.python3.7.site-packages.prompt_toolkit.filters',
              'venv.lib.python3.7.site-packages.prompt_toolkit.widgets',
              'venv.lib.python3.7.site-packages.prompt_toolkit.clipboard',
              'venv.lib.python3.7.site-packages.prompt_toolkit.eventloop',
              'venv.lib.python3.7.site-packages.prompt_toolkit.shortcuts',
              'venv.lib.python3.7.site-packages.prompt_toolkit.shortcuts.progress_bar',
              'venv.lib.python3.7.site-packages.prompt_toolkit.completion',
              'venv.lib.python3.7.site-packages.prompt_toolkit.application',
              'venv.lib.python3.7.site-packages.prompt_toolkit.key_binding',
              'venv.lib.python3.7.site-packages.prompt_toolkit.key_binding.bindings',
              'venv.lib.python3.7.site-packages.prompt_toolkit.formatted_text',
              'venv.lib.python3.7.site-packages.jupyter_console',
              'venv.lib.python3.7.site-packages.jupyter_console.tests',
              'venv.lib.python3.7.site-packages.ipython_genutils',
              'venv.lib.python3.7.site-packages.ipython_genutils.tests',
              'venv.lib.python3.7.site-packages.ipython_genutils.testing',
              'venv.lib.python3.7.site-packages.prometheus_client',
              'venv.lib.python3.7.site-packages.prometheus_client.bridge',
              'venv.lib.python3.7.site-packages.prometheus_client.twisted',
              'venv.lib.python3.7.site-packages.prometheus_client.openmetrics',
              'venv.lib.python3.7.site-packages.widgetsnbextension', 'venv.lib64.python3.7.site-packages.PIL',
              'venv.lib64.python3.7.site-packages.cv2', 'venv.lib64.python3.7.site-packages.cv2.data',
              'venv.lib64.python3.7.site-packages.pip', 'venv.lib64.python3.7.site-packages.pip._vendor',
              'venv.lib64.python3.7.site-packages.pip._vendor.idna',
              'venv.lib64.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib64.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib64.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib64.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib64.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib64.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib64.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib64.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib64.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib64.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib64.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib64.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib64.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib64.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib64.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib64.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib64.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib64.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib64.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib64.python3.7.site-packages.pip._vendor.progress',
              'venv.lib64.python3.7.site-packages.pip._vendor.requests',
              'venv.lib64.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib64.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib64.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib64.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib64.python3.7.site-packages.pip._internal',
              'venv.lib64.python3.7.site-packages.pip._internal.cli',
              'venv.lib64.python3.7.site-packages.pip._internal.req',
              'venv.lib64.python3.7.site-packages.pip._internal.vcs',
              'venv.lib64.python3.7.site-packages.pip._internal.utils',
              'venv.lib64.python3.7.site-packages.pip._internal.models',
              'venv.lib64.python3.7.site-packages.pip._internal.commands',
              'venv.lib64.python3.7.site-packages.pip._internal.operations', 'venv.lib64.python3.7.site-packages.tlz',
              'venv.lib64.python3.7.site-packages.zmq', 'venv.lib64.python3.7.site-packages.zmq.log',
              'venv.lib64.python3.7.site-packages.zmq.ssh', 'venv.lib64.python3.7.site-packages.zmq.auth',
              'venv.lib64.python3.7.site-packages.zmq.auth.asyncio', 'venv.lib64.python3.7.site-packages.zmq.green',
              'venv.lib64.python3.7.site-packages.zmq.green.eventloop', 'venv.lib64.python3.7.site-packages.zmq.sugar',
              'venv.lib64.python3.7.site-packages.zmq.tests', 'venv.lib64.python3.7.site-packages.zmq.tests.asyncio',
              'venv.lib64.python3.7.site-packages.zmq.utils', 'venv.lib64.python3.7.site-packages.zmq.asyncio',
              'venv.lib64.python3.7.site-packages.zmq.backend', 'venv.lib64.python3.7.site-packages.zmq.backend.cffi',
              'venv.lib64.python3.7.site-packages.zmq.backend.cython', 'venv.lib64.python3.7.site-packages.zmq.devices',
              'venv.lib64.python3.7.site-packages.zmq.eventloop',
              'venv.lib64.python3.7.site-packages.zmq.eventloop.minitornado',
              'venv.lib64.python3.7.site-packages.zmq.eventloop.minitornado.platform',
              'venv.lib64.python3.7.site-packages.dask', 'venv.lib64.python3.7.site-packages.dask.bag',
              'venv.lib64.python3.7.site-packages.dask.bag.tests', 'venv.lib64.python3.7.site-packages.dask.array',
              'venv.lib64.python3.7.site-packages.dask.array.tests', 'venv.lib64.python3.7.site-packages.dask.bytes',
              'venv.lib64.python3.7.site-packages.dask.bytes.tests', 'venv.lib64.python3.7.site-packages.dask.tests',
              'venv.lib64.python3.7.site-packages.dask.dataframe',
              'venv.lib64.python3.7.site-packages.dask.dataframe.io',
              'venv.lib64.python3.7.site-packages.dask.dataframe.io.tests',
              'venv.lib64.python3.7.site-packages.dask.dataframe.tests',
              'venv.lib64.python3.7.site-packages.dask.dataframe.tseries',
              'venv.lib64.python3.7.site-packages.dask.dataframe.tseries.tests',
              'venv.lib64.python3.7.site-packages.dask.diagnostics',
              'venv.lib64.python3.7.site-packages.dask.diagnostics.tests', 'venv.lib64.python3.7.site-packages.jedi',
              'venv.lib64.python3.7.site-packages.jedi.api', 'venv.lib64.python3.7.site-packages.jedi.common',
              'venv.lib64.python3.7.site-packages.jedi.evaluate',
              'venv.lib64.python3.7.site-packages.jedi.evaluate.context',
              'venv.lib64.python3.7.site-packages.jedi.evaluate.compiled',
              'venv.lib64.python3.7.site-packages.jedi.evaluate.compiled.subprocess',
              'venv.lib64.python3.7.site-packages.pytz', 'venv.lib64.python3.7.site-packages.pywt',
              'venv.lib64.python3.7.site-packages.pywt.data', 'venv.lib64.python3.7.site-packages.pywt._extensions',
              'venv.lib64.python3.7.site-packages.rope', 'venv.lib64.python3.7.site-packages.rope.base',
              'venv.lib64.python3.7.site-packages.rope.base.oi',
              'venv.lib64.python3.7.site-packages.rope.base.oi.type_hinting',
              'venv.lib64.python3.7.site-packages.rope.base.oi.type_hinting.providers',
              'venv.lib64.python3.7.site-packages.rope.base.oi.type_hinting.resolvers',
              'venv.lib64.python3.7.site-packages.rope.base.utils', 'venv.lib64.python3.7.site-packages.rope.contrib',
              'venv.lib64.python3.7.site-packages.rope.refactor',
              'venv.lib64.python3.7.site-packages.rope.refactor.importutils',
              'venv.lib64.python3.7.site-packages.parso', 'venv.lib64.python3.7.site-packages.parso.pgen2',
              'venv.lib64.python3.7.site-packages.parso.python', 'venv.lib64.python3.7.site-packages.scipy',
              'venv.lib64.python3.7.site-packages.scipy.io', 'venv.lib64.python3.7.site-packages.scipy.io.arff',
              'venv.lib64.python3.7.site-packages.scipy.io.arff.tests',
              'venv.lib64.python3.7.site-packages.scipy.io.tests', 'venv.lib64.python3.7.site-packages.scipy.io.matlab',
              'venv.lib64.python3.7.site-packages.scipy.io.matlab.tests',
              'venv.lib64.python3.7.site-packages.scipy.io.harwell_boeing',
              'venv.lib64.python3.7.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib64.python3.7.site-packages.scipy.odr', 'venv.lib64.python3.7.site-packages.scipy.odr.tests',
              'venv.lib64.python3.7.site-packages.scipy._lib', 'venv.lib64.python3.7.site-packages.scipy._lib.tests',
              'venv.lib64.python3.7.site-packages.scipy.misc', 'venv.lib64.python3.7.site-packages.scipy.misc.tests',
              'venv.lib64.python3.7.site-packages.scipy.stats', 'venv.lib64.python3.7.site-packages.scipy.stats.tests',
              'venv.lib64.python3.7.site-packages.scipy.linalg',
              'venv.lib64.python3.7.site-packages.scipy.linalg.tests',
              'venv.lib64.python3.7.site-packages.scipy.signal',
              'venv.lib64.python3.7.site-packages.scipy.signal.tests',
              'venv.lib64.python3.7.site-packages.scipy.signal.windows',
              'venv.lib64.python3.7.site-packages.scipy.sparse',
              'venv.lib64.python3.7.site-packages.scipy.sparse.tests',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.tests',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib64.python3.7.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib64.python3.7.site-packages.scipy.sparse.csgraph',
              'venv.lib64.python3.7.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib64.python3.7.site-packages.scipy.cluster',
              'venv.lib64.python3.7.site-packages.scipy.cluster.tests',
              'venv.lib64.python3.7.site-packages.scipy.fftpack',
              'venv.lib64.python3.7.site-packages.scipy.fftpack.tests',
              'venv.lib64.python3.7.site-packages.scipy.ndimage',
              'venv.lib64.python3.7.site-packages.scipy.ndimage.tests',
              'venv.lib64.python3.7.site-packages.scipy.spatial',
              'venv.lib64.python3.7.site-packages.scipy.spatial.tests',
              'venv.lib64.python3.7.site-packages.scipy.spatial.transform',
              'venv.lib64.python3.7.site-packages.scipy.spatial.transform.tests',
              'venv.lib64.python3.7.site-packages.scipy.special',
              'venv.lib64.python3.7.site-packages.scipy.special.tests',
              'venv.lib64.python3.7.site-packages.scipy.special._precompute',
              'venv.lib64.python3.7.site-packages.scipy.optimize',
              'venv.lib64.python3.7.site-packages.scipy.optimize._lsq',
              'venv.lib64.python3.7.site-packages.scipy.optimize.tests',
              'venv.lib64.python3.7.site-packages.scipy.optimize._trlib',
              'venv.lib64.python3.7.site-packages.scipy.optimize._shgo_lib',
              'venv.lib64.python3.7.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib64.python3.7.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib64.python3.7.site-packages.scipy.constants',
              'venv.lib64.python3.7.site-packages.scipy.constants.tests',
              'venv.lib64.python3.7.site-packages.scipy.integrate',
              'venv.lib64.python3.7.site-packages.scipy.integrate._ivp',
              'venv.lib64.python3.7.site-packages.scipy.integrate.tests',
              'venv.lib64.python3.7.site-packages.scipy.interpolate',
              'venv.lib64.python3.7.site-packages.scipy.interpolate.tests',
              'venv.lib64.python3.7.site-packages.scipy._build_utils', 'venv.lib64.python3.7.site-packages.toolz',
              'venv.lib64.python3.7.site-packages.toolz.curried', 'venv.lib64.python3.7.site-packages.toolz.sandbox',
              'venv.lib64.python3.7.site-packages.bleach', 'venv.lib64.python3.7.site-packages.bleach._vendor',
              'venv.lib64.python3.7.site-packages.bleach._vendor.html5lib',
              'venv.lib64.python3.7.site-packages.bleach._vendor.html5lib._trie',
              'venv.lib64.python3.7.site-packages.bleach._vendor.html5lib.filters',
              'venv.lib64.python3.7.site-packages.bleach._vendor.html5lib.treewalkers',
              'venv.lib64.python3.7.site-packages.bleach._vendor.html5lib.treeadapters',
              'venv.lib64.python3.7.site-packages.bleach._vendor.html5lib.treebuilders',
              'venv.lib64.python3.7.site-packages.imgaug', 'venv.lib64.python3.7.site-packages.imgaug.external',
              'venv.lib64.python3.7.site-packages.imgaug.augmenters', 'venv.lib64.python3.7.site-packages.jinja2',
              'venv.lib64.python3.7.site-packages.pandas', 'venv.lib64.python3.7.site-packages.pandas.io',
              'venv.lib64.python3.7.site-packages.pandas.io.sas', 'venv.lib64.python3.7.site-packages.pandas.io.json',
              'venv.lib64.python3.7.site-packages.pandas.io.formats',
              'venv.lib64.python3.7.site-packages.pandas.io.msgpack',
              'venv.lib64.python3.7.site-packages.pandas.io.clipboard', 'venv.lib64.python3.7.site-packages.pandas.api',
              'venv.lib64.python3.7.site-packages.pandas.api.types',
              'venv.lib64.python3.7.site-packages.pandas.api.extensions',
              'venv.lib64.python3.7.site-packages.pandas.core', 'venv.lib64.python3.7.site-packages.pandas.core.util',
              'venv.lib64.python3.7.site-packages.pandas.core.tools',
              'venv.lib64.python3.7.site-packages.pandas.core.arrays',
              'venv.lib64.python3.7.site-packages.pandas.core.dtypes',
              'venv.lib64.python3.7.site-packages.pandas.core.sparse',
              'venv.lib64.python3.7.site-packages.pandas.core.groupby',
              'venv.lib64.python3.7.site-packages.pandas.core.indexes',
              'venv.lib64.python3.7.site-packages.pandas.core.reshape',
              'venv.lib64.python3.7.site-packages.pandas.core.internals',
              'venv.lib64.python3.7.site-packages.pandas.core.computation',
              'venv.lib64.python3.7.site-packages.pandas.util', 'venv.lib64.python3.7.site-packages.pandas._libs',
              'venv.lib64.python3.7.site-packages.pandas._libs.tslibs',
              'venv.lib64.python3.7.site-packages.pandas.tests', 'venv.lib64.python3.7.site-packages.pandas.tests.io',
              'venv.lib64.python3.7.site-packages.pandas.tests.io.sas',
              'venv.lib64.python3.7.site-packages.pandas.tests.io.json',
              'venv.lib64.python3.7.site-packages.pandas.tests.io.parser',
              'venv.lib64.python3.7.site-packages.pandas.tests.io.formats',
              'venv.lib64.python3.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib64.python3.7.site-packages.pandas.tests.api',
              'venv.lib64.python3.7.site-packages.pandas.tests.util',
              'venv.lib64.python3.7.site-packages.pandas.tests.frame',
              'venv.lib64.python3.7.site-packages.pandas.tests.tools',
              'venv.lib64.python3.7.site-packages.pandas.tests.arrays',
              'venv.lib64.python3.7.site-packages.pandas.tests.arrays.sparse',
              'venv.lib64.python3.7.site-packages.pandas.tests.arrays.interval',
              'venv.lib64.python3.7.site-packages.pandas.tests.arrays.categorical',
              'venv.lib64.python3.7.site-packages.pandas.tests.dtypes',
              'venv.lib64.python3.7.site-packages.pandas.tests.dtypes.cast',
              'venv.lib64.python3.7.site-packages.pandas.tests.scalar',
              'venv.lib64.python3.7.site-packages.pandas.tests.scalar.period',
              'venv.lib64.python3.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib64.python3.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib64.python3.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib64.python3.7.site-packages.pandas.tests.series',
              'venv.lib64.python3.7.site-packages.pandas.tests.series.indexing',
              'venv.lib64.python3.7.site-packages.pandas.tests.sparse',
              'venv.lib64.python3.7.site-packages.pandas.tests.sparse.frame',
              'venv.lib64.python3.7.site-packages.pandas.tests.sparse.series',
              'venv.lib64.python3.7.site-packages.pandas.tests.tslibs',
              'venv.lib64.python3.7.site-packages.pandas.tests.generic',
              'venv.lib64.python3.7.site-packages.pandas.tests.groupby',
              'venv.lib64.python3.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexes',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexes.multi',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexes.period',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib64.python3.7.site-packages.pandas.tests.reshape',
              'venv.lib64.python3.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib64.python3.7.site-packages.pandas.tests.tseries',
              'venv.lib64.python3.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexing',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib64.python3.7.site-packages.pandas.tests.indexing.multiindex',
              'venv.lib64.python3.7.site-packages.pandas.tests.plotting',
              'venv.lib64.python3.7.site-packages.pandas.tests.resample',
              'venv.lib64.python3.7.site-packages.pandas.tests.extension',
              'venv.lib64.python3.7.site-packages.pandas.tests.extension.base',
              'venv.lib64.python3.7.site-packages.pandas.tests.extension.json',
              'venv.lib64.python3.7.site-packages.pandas.tests.extension.arrow',
              'venv.lib64.python3.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib64.python3.7.site-packages.pandas.tests.internals',
              'venv.lib64.python3.7.site-packages.pandas.tests.arithmetic',
              'venv.lib64.python3.7.site-packages.pandas.tests.reductions',
              'venv.lib64.python3.7.site-packages.pandas.tests.computation',
              'venv.lib64.python3.7.site-packages.pandas.arrays', 'venv.lib64.python3.7.site-packages.pandas.compat',
              'venv.lib64.python3.7.site-packages.pandas.compat.numpy',
              'venv.lib64.python3.7.site-packages.pandas.errors', 'venv.lib64.python3.7.site-packages.pandas.tseries',
              'venv.lib64.python3.7.site-packages.pandas.plotting', 'venv.lib64.python3.7.site-packages.tables',
              'venv.lib64.python3.7.site-packages.tables.misc', 'venv.lib64.python3.7.site-packages.tables.nodes',
              'venv.lib64.python3.7.site-packages.tables.nodes.tests',
              'venv.lib64.python3.7.site-packages.tables.tests', 'venv.lib64.python3.7.site-packages.tables.scripts',
              'venv.lib64.python3.7.site-packages.IPython', 'venv.lib64.python3.7.site-packages.IPython.lib',
              'venv.lib64.python3.7.site-packages.IPython.lib.tests', 'venv.lib64.python3.7.site-packages.IPython.core',
              'venv.lib64.python3.7.site-packages.IPython.core.tests',
              'venv.lib64.python3.7.site-packages.IPython.core.magics',
              'venv.lib64.python3.7.site-packages.IPython.utils',
              'venv.lib64.python3.7.site-packages.IPython.utils.tests',
              'venv.lib64.python3.7.site-packages.IPython.kernel', 'venv.lib64.python3.7.site-packages.IPython.testing',
              'venv.lib64.python3.7.site-packages.IPython.testing.tests',
              'venv.lib64.python3.7.site-packages.IPython.testing.plugin',
              'venv.lib64.python3.7.site-packages.IPython.external',
              'venv.lib64.python3.7.site-packages.IPython.external.decorators',
              'venv.lib64.python3.7.site-packages.IPython.terminal',
              'venv.lib64.python3.7.site-packages.IPython.terminal.tests',
              'venv.lib64.python3.7.site-packages.IPython.terminal.pt_inputhooks',
              'venv.lib64.python3.7.site-packages.IPython.sphinxext',
              'venv.lib64.python3.7.site-packages.IPython.extensions',
              'venv.lib64.python3.7.site-packages.IPython.extensions.tests',
              'venv.lib64.python3.7.site-packages.imageio', 'venv.lib64.python3.7.site-packages.imageio.core',
              'venv.lib64.python3.7.site-packages.imageio.plugins', 'venv.lib64.python3.7.site-packages.numexpr',
              'venv.lib64.python3.7.site-packages.numexpr.tests', 'venv.lib64.python3.7.site-packages.pexpect',
              'venv.lib64.python3.7.site-packages.shapely', 'venv.lib64.python3.7.site-packages.shapely.examples',
              'venv.lib64.python3.7.site-packages.shapely.geometry',
              'venv.lib64.python3.7.site-packages.shapely.speedups',
              'venv.lib64.python3.7.site-packages.shapely.algorithms',
              'venv.lib64.python3.7.site-packages.shapely.vectorized', 'venv.lib64.python3.7.site-packages.skimage',
              'venv.lib64.python3.7.site-packages.skimage.io', 'venv.lib64.python3.7.site-packages.skimage.io.tests',
              'venv.lib64.python3.7.site-packages.skimage.io._plugins',
              'venv.lib64.python3.7.site-packages.skimage.data',
              'venv.lib64.python3.7.site-packages.skimage.data.tests',
              'venv.lib64.python3.7.site-packages.skimage.draw',
              'venv.lib64.python3.7.site-packages.skimage.draw.tests',
              'venv.lib64.python3.7.site-packages.skimage.util',
              'venv.lib64.python3.7.site-packages.skimage.util.tests',
              'venv.lib64.python3.7.site-packages.skimage.color',
              'venv.lib64.python3.7.site-packages.skimage.color.tests',
              'venv.lib64.python3.7.site-packages.skimage.graph',
              'venv.lib64.python3.7.site-packages.skimage.graph.tests',
              'venv.lib64.python3.7.site-packages.skimage.future',
              'venv.lib64.python3.7.site-packages.skimage.future.graph',
              'venv.lib64.python3.7.site-packages.skimage.novice',
              'venv.lib64.python3.7.site-packages.skimage.novice.tests',
              'venv.lib64.python3.7.site-packages.skimage.viewer',
              'venv.lib64.python3.7.site-packages.skimage.viewer.tests',
              'venv.lib64.python3.7.site-packages.skimage.viewer.utils',
              'venv.lib64.python3.7.site-packages.skimage.viewer.plugins',
              'venv.lib64.python3.7.site-packages.skimage.viewer.viewers',
              'venv.lib64.python3.7.site-packages.skimage.viewer.widgets',
              'venv.lib64.python3.7.site-packages.skimage.viewer.canvastools',
              'venv.lib64.python3.7.site-packages.skimage._shared',
              'venv.lib64.python3.7.site-packages.skimage._shared.tests',
              'venv.lib64.python3.7.site-packages.skimage.feature',
              'venv.lib64.python3.7.site-packages.skimage.feature.tests',
              'venv.lib64.python3.7.site-packages.skimage.filters',
              'venv.lib64.python3.7.site-packages.skimage.filters.rank',
              'venv.lib64.python3.7.site-packages.skimage.filters.rank.tests',
              'venv.lib64.python3.7.site-packages.skimage.filters.tests',
              'venv.lib64.python3.7.site-packages.skimage.measure',
              'venv.lib64.python3.7.site-packages.skimage.measure.tests',
              'venv.lib64.python3.7.site-packages.skimage.scripts',
              'venv.lib64.python3.7.site-packages.skimage.exposure',
              'venv.lib64.python3.7.site-packages.skimage.exposure.tests',
              'venv.lib64.python3.7.site-packages.skimage.external',
              'venv.lib64.python3.7.site-packages.skimage.external.tifffile',
              'venv.lib64.python3.7.site-packages.skimage.transform',
              'venv.lib64.python3.7.site-packages.skimage.transform.tests',
              'venv.lib64.python3.7.site-packages.skimage.morphology',
              'venv.lib64.python3.7.site-packages.skimage.morphology.tests',
              'venv.lib64.python3.7.site-packages.skimage.restoration',
              'venv.lib64.python3.7.site-packages.skimage.restoration.tests',
              'venv.lib64.python3.7.site-packages.skimage.segmentation',
              'venv.lib64.python3.7.site-packages.skimage.segmentation.tests',
              'venv.lib64.python3.7.site-packages.tornado', 'venv.lib64.python3.7.site-packages.tornado.test',
              'venv.lib64.python3.7.site-packages.tornado.platform', 'venv.lib64.python3.7.site-packages.wcwidth',
              'venv.lib64.python3.7.site-packages.wcwidth.tests', 'venv.lib64.python3.7.site-packages.backcall',
              'venv.lib64.python3.7.site-packages.nbformat', 'venv.lib64.python3.7.site-packages.nbformat.v1',
              'venv.lib64.python3.7.site-packages.nbformat.v1.tests', 'venv.lib64.python3.7.site-packages.nbformat.v2',
              'venv.lib64.python3.7.site-packages.nbformat.v2.tests', 'venv.lib64.python3.7.site-packages.nbformat.v3',
              'venv.lib64.python3.7.site-packages.nbformat.v3.tests', 'venv.lib64.python3.7.site-packages.nbformat.v4',
              'venv.lib64.python3.7.site-packages.nbformat.v4.tests',
              'venv.lib64.python3.7.site-packages.nbformat.tests', 'venv.lib64.python3.7.site-packages.networkx',
              'venv.lib64.python3.7.site-packages.networkx.tests', 'venv.lib64.python3.7.site-packages.networkx.utils',
              'venv.lib64.python3.7.site-packages.networkx.linalg',
              'venv.lib64.python3.7.site-packages.networkx.classes',
              'venv.lib64.python3.7.site-packages.networkx.drawing',
              'venv.lib64.python3.7.site-packages.networkx.testing',
              'venv.lib64.python3.7.site-packages.networkx.readwrite',
              'venv.lib64.python3.7.site-packages.networkx.readwrite.json_graph',
              'venv.lib64.python3.7.site-packages.networkx.algorithms',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.flow',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.tree',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.coloring',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.bipartite',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.community',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.operators',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.traversal',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.centrality',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.components',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.isomorphism',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.connectivity',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.approximation',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.assortativity',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.link_analysis',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.shortest_paths',
              'venv.lib64.python3.7.site-packages.networkx.algorithms.node_classification',
              'venv.lib64.python3.7.site-packages.networkx.generators', 'venv.lib64.python3.7.site-packages.notebook',
              'venv.lib64.python3.7.site-packages.notebook.auth',
              'venv.lib64.python3.7.site-packages.notebook.auth.tests',
              'venv.lib64.python3.7.site-packages.notebook.base', 'venv.lib64.python3.7.site-packages.notebook.edit',
              'venv.lib64.python3.7.site-packages.notebook.i18n', 'venv.lib64.python3.7.site-packages.notebook.tree',
              'venv.lib64.python3.7.site-packages.notebook.tree.tests',
              'venv.lib64.python3.7.site-packages.notebook.view', 'venv.lib64.python3.7.site-packages.notebook.files',
              'venv.lib64.python3.7.site-packages.notebook.tests',
              'venv.lib64.python3.7.site-packages.notebook.tests.selenium',
              'venv.lib64.python3.7.site-packages.notebook.bundler',
              'venv.lib64.python3.7.site-packages.notebook.bundler.tests',
              'venv.lib64.python3.7.site-packages.notebook.notebook',
              'venv.lib64.python3.7.site-packages.notebook.services',
              'venv.lib64.python3.7.site-packages.notebook.services.api',
              'venv.lib64.python3.7.site-packages.notebook.services.api.tests',
              'venv.lib64.python3.7.site-packages.notebook.services.config',
              'venv.lib64.python3.7.site-packages.notebook.services.config.tests',
              'venv.lib64.python3.7.site-packages.notebook.services.kernels',
              'venv.lib64.python3.7.site-packages.notebook.services.kernels.tests',
              'venv.lib64.python3.7.site-packages.notebook.services.contents',
              'venv.lib64.python3.7.site-packages.notebook.services.contents.tests',
              'venv.lib64.python3.7.site-packages.notebook.services.security',
              'venv.lib64.python3.7.site-packages.notebook.services.sessions',
              'venv.lib64.python3.7.site-packages.notebook.services.sessions.tests',
              'venv.lib64.python3.7.site-packages.notebook.services.nbconvert',
              'venv.lib64.python3.7.site-packages.notebook.services.nbconvert.tests',
              'venv.lib64.python3.7.site-packages.notebook.services.kernelspecs',
              'venv.lib64.python3.7.site-packages.notebook.services.kernelspecs.tests',
              'venv.lib64.python3.7.site-packages.notebook.terminal',
              'venv.lib64.python3.7.site-packages.notebook.nbconvert',
              'venv.lib64.python3.7.site-packages.notebook.nbconvert.tests',
              'venv.lib64.python3.7.site-packages.notebook.kernelspecs', 'venv.lib64.python3.7.site-packages.pygments',
              'venv.lib64.python3.7.site-packages.pygments.lexers',
              'venv.lib64.python3.7.site-packages.pygments.styles',
              'venv.lib64.python3.7.site-packages.pygments.filters',
              'venv.lib64.python3.7.site-packages.pygments.formatters', 'venv.lib64.python3.7.site-packages.testpath',
              'venv.lib64.python3.7.site-packages.ipykernel', 'venv.lib64.python3.7.site-packages.ipykernel.gui',
              'venv.lib64.python3.7.site-packages.ipykernel.comm', 'venv.lib64.python3.7.site-packages.ipykernel.pylab',
              'venv.lib64.python3.7.site-packages.ipykernel.tests',
              'venv.lib64.python3.7.site-packages.ipykernel.inprocess',
              'venv.lib64.python3.7.site-packages.ipykernel.inprocess.tests',
              'venv.lib64.python3.7.site-packages.nbconvert', 'venv.lib64.python3.7.site-packages.nbconvert.tests',
              'venv.lib64.python3.7.site-packages.nbconvert.utils',
              'venv.lib64.python3.7.site-packages.nbconvert.utils.tests',
              'venv.lib64.python3.7.site-packages.nbconvert.filters',
              'venv.lib64.python3.7.site-packages.nbconvert.filters.tests',
              'venv.lib64.python3.7.site-packages.nbconvert.writers',
              'venv.lib64.python3.7.site-packages.nbconvert.writers.tests',
              'venv.lib64.python3.7.site-packages.nbconvert.exporters',
              'venv.lib64.python3.7.site-packages.nbconvert.exporters.tests',
              'venv.lib64.python3.7.site-packages.nbconvert.resources',
              'venv.lib64.python3.7.site-packages.nbconvert.preprocessors',
              'venv.lib64.python3.7.site-packages.nbconvert.preprocessors.tests',
              'venv.lib64.python3.7.site-packages.nbconvert.postprocessors',
              'venv.lib64.python3.7.site-packages.nbconvert.postprocessors.tests',
              'venv.lib64.python3.7.site-packages.qtconsole', 'venv.lib64.python3.7.site-packages.qtconsole.tests',
              'venv.lib64.python3.7.site-packages.terminado', 'venv.lib64.python3.7.site-packages.terminado.tests',
              'venv.lib64.python3.7.site-packages.traitlets', 'venv.lib64.python3.7.site-packages.traitlets.tests',
              'venv.lib64.python3.7.site-packages.traitlets.utils',
              'venv.lib64.python3.7.site-packages.traitlets.utils.tests',
              'venv.lib64.python3.7.site-packages.traitlets.config',
              'venv.lib64.python3.7.site-packages.traitlets.config.tests',
              'venv.lib64.python3.7.site-packages.defusedxml', 'venv.lib64.python3.7.site-packages.ipywidgets',
              'venv.lib64.python3.7.site-packages.ipywidgets.tests',
              'venv.lib64.python3.7.site-packages.ipywidgets.widgets',
              'venv.lib64.python3.7.site-packages.ipywidgets.widgets.tests',
              'venv.lib64.python3.7.site-packages.markupsafe', 'venv.lib64.python3.7.site-packages.matplotlib',
              'venv.lib64.python3.7.site-packages.matplotlib.tri', 'venv.lib64.python3.7.site-packages.matplotlib.axes',
              'venv.lib64.python3.7.site-packages.matplotlib.cbook',
              'venv.lib64.python3.7.site-packages.matplotlib.style',
              'venv.lib64.python3.7.site-packages.matplotlib.tests',
              'venv.lib64.python3.7.site-packages.matplotlib.compat',
              'venv.lib64.python3.7.site-packages.matplotlib.testing',
              'venv.lib64.python3.7.site-packages.matplotlib.testing.jpl_units',
              'venv.lib64.python3.7.site-packages.matplotlib.backends',
              'venv.lib64.python3.7.site-packages.matplotlib.backends.qt_editor',
              'venv.lib64.python3.7.site-packages.matplotlib.sphinxext',
              'venv.lib64.python3.7.site-packages.matplotlib.sphinxext.tests',
              'venv.lib64.python3.7.site-packages.matplotlib.projections',
              'venv.lib64.python3.7.site-packages.ptyprocess', 'venv.lib64.python3.7.site-packages.send2trash',
              'venv.lib64.python3.7.site-packages.setuptools', 'venv.lib64.python3.7.site-packages.setuptools.extern',
              'venv.lib64.python3.7.site-packages.setuptools._vendor',
              'venv.lib64.python3.7.site-packages.setuptools._vendor.packaging',
              'venv.lib64.python3.7.site-packages.setuptools.command', 'venv.lib64.python3.7.site-packages.cloudpickle',
              'venv.lib64.python3.7.site-packages.jupyter_core',
              'venv.lib64.python3.7.site-packages.jupyter_core.tests',
              'venv.lib64.python3.7.site-packages.jupyter_core.utils',
              'venv.lib64.python3.7.site-packages.mpl_toolkits.tests',
              'venv.lib64.python3.7.site-packages.mpl_toolkits.mplot3d',
              'venv.lib64.python3.7.site-packages.mpl_toolkits.axes_grid',
              'venv.lib64.python3.7.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib64.python3.7.site-packages.mpl_toolkits.axisartist',
              'venv.lib64.python3.7.site-packages.webencodings', 'venv.lib64.python3.7.site-packages.pkg_resources',
              'venv.lib64.python3.7.site-packages.pkg_resources.extern',
              'venv.lib64.python3.7.site-packages.pkg_resources._vendor',
              'venv.lib64.python3.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib64.python3.7.site-packages.jupyter_client',
              'venv.lib64.python3.7.site-packages.jupyter_client.tests',
              'venv.lib64.python3.7.site-packages.jupyter_client.ioloop',
              'venv.lib64.python3.7.site-packages.jupyter_client.blocking',
              'venv.lib64.python3.7.site-packages.prompt_toolkit',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.input',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.layout',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.lexers',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.output',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.styles',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.contrib',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.contrib.telnet',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.contrib.completers',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.filters',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.widgets',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.clipboard',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.eventloop',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.shortcuts',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.shortcuts.progress_bar',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.completion',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.application',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.key_binding',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.key_binding.bindings',
              'venv.lib64.python3.7.site-packages.prompt_toolkit.formatted_text',
              'venv.lib64.python3.7.site-packages.jupyter_console',
              'venv.lib64.python3.7.site-packages.jupyter_console.tests',
              'venv.lib64.python3.7.site-packages.ipython_genutils',
              'venv.lib64.python3.7.site-packages.ipython_genutils.tests',
              'venv.lib64.python3.7.site-packages.ipython_genutils.testing',
              'venv.lib64.python3.7.site-packages.prometheus_client',
              'venv.lib64.python3.7.site-packages.prometheus_client.bridge',
              'venv.lib64.python3.7.site-packages.prometheus_client.twisted',
              'venv.lib64.python3.7.site-packages.prometheus_client.openmetrics',
              'venv.lib64.python3.7.site-packages.widgetsnbextension', 'maths', 'tests', 'tests.unit', 'structures',
              'neural_network'],
    url='',
    license='',
    author='mipo57',
    author_email='',
    description=''
)
